name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      all:
        description: Force NX to run all tasks on all projects
        type: boolean
        required: false
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Git
        run: |
          git config user.name "CPD Bot"
          git config user.email "cpd@duck.com"

      - name: Install
        run: npm ci

      - name: Lint
        run: npx nx affected -t lint --all=${{ github.event.inputs.all }}

      - name: Test
        run: npx nx affected -t test --all=${{ github.event.inputs.all }}

      - name: Build
        run: npx nx affected -t build --all=${{ github.event.inputs.all }}

      - name: Version
        run: npx nx affected -t version --all=${{ github.event.inputs.all }} --parallel 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup NPM
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npx nx affected -t deploy --all=${{ github.event.inputs.all }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
