name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Lint
        run: npx nx affected -t lint

      - name: Test
        run: npx nx affected -t test

      - name: Build
        run: npx nx affected -t build
