name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      all:
        description: Force NX to run all tasks on all projects
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Git
        run: |
          git config user.name "CPD Bot"
          git config user.email "cpd@duck.com"

      - name: Install
        run: npm ci

      - name: Lint
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false  }} \
          -t=lint

      - name: Test
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false }} \
          -t=test

      - name: Build
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false  }} \
          -t=build

      - name: Version
        run: |
          git pull --tags
          npx nx affected \
          -t=version \
          --parallel=1 \
          --all=${{ github.event.inputs.all || false  }} \
          --allowEmptyRelease=${{ github.event.inputs.all || false  }}
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup NPM
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false  }} \
          -t=deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
