name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dryRun:
        description: Run the publish workflow without publishing
        type: boolean
        required: false
        default: true
      releaseAs:
        description: Force a release of a specific version on all packages
        type: choice
        required: true
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
      all:
        description: Force NX scripts to run on all packages
        type: boolean
        required: false
        default: true

jobs:
  publish-affected-packages:
    name: Publish Affected Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup, Format, Lint, Test & Build
        uses: ./.github/actions/setup-format-lint-test-build
        with:
          all: ${{ github.event.inputs.all || false  }}

      - name: Version Auto
        if: ${{ !github.event.inputs.releaseAs }}
        run: |
          npx nx affected \
          -t=version \
          --parallel=1 \
          --all=${{ github.event.inputs.all || false  }} \
          --allowEmptyRelease=true \
          --noVerify \
          --push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup NPM
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Version Manual
        if: github.event.inputs.releaseAs
        run: |
          npx nx affected \
          -t=version \
          --parallel=1 \
          --allowEmptyRelease=${{ github.event.inputs.all || false  }} \
          --dryRun=${{ github.event.inputs.dryRun || false  }} \
          --releaseAs=${{ github.event.inputs.releaseAs }} \
          --all=${{ github.event.inputs.all || false  }} \
          --postTargets=deploy \
          --noVerify \
          --push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
