name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      all:
        description: Force NX scripts to run on all packages
        type: boolean
        required: false
        default: true

jobs:
  setup_format_lint_test_build:
    name: Setup, Format, Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup Git
        run: |
          git config user.name "CPD Bot"
          git config user.email "cpd@duck.com"

      - name: Install
        run: npm ci

      - name: Format
        run: npx nx format:check

      - name: Lint
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false  }} \
          -t=lint

      - name: Test
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false }} \
          -t=test

      - name: Build
        run: |
          npx nx affected \
          --all=${{ github.event.inputs.all || false  }} \
          -t=build
